// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEmRVLYCEgWV3zo8kTA4pJLp990zLJlkY',
    appId: '1:818633131562:web:4b62c68d9090170e9a2553',
    messagingSenderId: '818633131562',
    projectId: 'campus-connect-bebef',
    authDomain: 'campus-connect-bebef.firebaseapp.com',
    storageBucket: 'campus-connect-bebef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIB3Mb4FPzKeuq-zbmr8gdZpLY5R4hdiU',
    appId: '1:818633131562:android:ec938ff37bbb1d819a2553',
    messagingSenderId: '818633131562',
    projectId: 'campus-connect-bebef',
    storageBucket: 'campus-connect-bebef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR7JpJwcZug3JjhjE6WiVZBW5qO1j3Pbo',
    appId: '1:818633131562:ios:148a85a62d7945fc9a2553',
    messagingSenderId: '818633131562',
    projectId: 'campus-connect-bebef',
    storageBucket: 'campus-connect-bebef.firebasestorage.app',
    iosBundleId: 'com.example.campusconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR7JpJwcZug3JjhjE6WiVZBW5qO1j3Pbo',
    appId: '1:818633131562:ios:148a85a62d7945fc9a2553',
    messagingSenderId: '818633131562',
    projectId: 'campus-connect-bebef',
    storageBucket: 'campus-connect-bebef.firebasestorage.app',
    iosBundleId: 'com.example.campusconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEmRVLYCEgWV3zo8kTA4pJLp990zLJlkY',
    appId: '1:818633131562:web:8ebc18ee3aa764569a2553',
    messagingSenderId: '818633131562',
    projectId: 'campus-connect-bebef',
    authDomain: 'campus-connect-bebef.firebaseapp.com',
    storageBucket: 'campus-connect-bebef.firebasestorage.app',
  );
}
